# configs/model/qwen8b_3b_critic.yaml
# [V-FINAL - Actor-based Encoder]
# 不再需要为encoder指定默认配置

defaults:
  - critic: qwen3b
  - token_reward_model: qwen1.8b_trm
  - lora_config_default  # [FIX] 引用可重用的LoRA配置

# Actor 配置 (保持不变)
name: "qwen7b"
path: "models/Qwen2.5-7B-Instruct"
use_lora: true
